services:
  web:
    build: .
    container_name: codeigniter_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"